In [1]:
from __future__ import annotations

import json
from collections import defaultdict
from collections.abc import Iterable
from pathlib import Path

import numpy as np
import pandas as pd
import plotly.express as px
from kebab.utils.dataset.wikidata.wikidata_utils import ResolvedWikidataEntity
from kebab.utils.io_helpers import resolve_path

In [2]:
# whether to save statistics as JSON files
save_statistics = False

In [ ]:
# (fragments or pairs)
# dataset_path = Path.cwd().parent / "data" / "REBEL" / "linking" / "test" / "rebel_linking_dataset.jsonl"
dataset_path = (
    Path.cwd().parent / "data" / "REBEL" / "entity_generation" / "test" / "rebel_entity_generation_dataset.jsonl"
)

# # entity map
# fragment_to_entity_map_path = (
#     Path.cwd().parent / "data" / "REBEL" / "data" / "linking" / "base" / "rebel_fragment_to_entity_map.jsonl"
# )

# fragment_to_entity_map = defaultdict(list)
# with open(fragment_to_entity_map_path, "r", encoding="utf-8") as f:
#     for line in f:
#         fragment_id, entity_id = json.loads(line)
#         fragment_to_entity_map[fragment_id] = entity_id

# print(f"Loaded entity map for {len(fragment_to_entity_map)} fragments.")

Load the fragments

In [4]:
fragments = []

# we will not be using fragments with no names
fragments_with_no_names = 0


def load_jsonl(file_path: Path) -> Iterable[ResolvedWikidataEntity]:
    """Load a jsonl file containing either ResolvedWikidataEntity objects or tuples of such objects."""
    is_tuples = None

    with open(file_path, encoding="utf-8") as f:
        for line in f:
            if is_tuples is None:
                t = json.loads(line)
                is_tuples = isinstance(t, list)

            if is_tuples:
                left, right = json.loads(line)
                yield ResolvedWikidataEntity.from_dict(left)
                yield ResolvedWikidataEntity.from_dict(right)
            else:
                yield ResolvedWikidataEntity.from_json(line)


seen = set()

for fragment in load_jsonl(dataset_path):
    if not fragment.names:
        fragments_with_no_names += 1
        del fragment
        continue

    prop_str = fragment.property_values_str()

    if prop_str in seen:
        del fragment
        continue

    seen.add(prop_str)

    if not fragment.entity_id and "entity_id" in fragment.metadata:
        fragment.entity_id = fragment.metadata["entity_id"]

    # reduce memory footprint
    if "entity_id" in fragment.metadata:
        del fragment.metadata["entity_id"]

    if "fragment_id" in fragment.metadata:
        del fragment.metadata["fragment_id"]

    if "fragment_ids" in fragment.metadata:
        del fragment.metadata["fragment_ids"]

    fragment.evidence_map = None  # type: ignore
    fragment.source_ids = None  # type: ignore

    fragments.append(fragment)

print(f"Loaded {len(fragments):,d} fragments, ignored {fragments_with_no_names:,d} fragments with no names")

Loaded 5,108 fragments, ignored 0 fragments with no names

Example fragment

In [5]:
fragments[0]

ResolvedWikidataEntity(entity_id='Q100048', properties=defaultdict(<class 'list'>, {'name': ['Concordia sulla Secchia', 'Concordia'], 'instance of': ['comune'], 'located in the administrative territorial entity': ['Province of Modena'], 'country': ['Italian'], 'shares border with': ['Mirandola', 'Moglia', 'Novi di Modena', 'Quistello', 'San Giacomo delle Segnate', 'San Giovanni del Dosso', 'San Possidonio']}), source_ids=None, evidence_map=None, metadata={'merge_count': 7, 'type': ['commune of Italy'], 'title': 'Concordia sulla Secchia'})

In [22]:
filtered = []

for fragment in fragments:
    if "point in time" in fragment.properties:
        continue

    names = set(fragment.names)
    found = False
    for prop_name, prop_values in fragment.properties.items():
        if found:
            break

        if prop_name == "name":
            continue

        for v in prop_values:
            if v in names:
                filtered.append(fragment)
                print(f"'{v}' found in '{prop_name}':")
                # print("Names: " + str(fragment.names))
                print(dict(fragment.properties))
                print(fragment.metadata)
                print()
                found = True

                break

print(f"Filtered down to {len(filtered):,d} fragments where a property value matches a name")

'Ostia' found in 'location':
{'name': ['Ostia', 'Ostia Antica', 'Ostian', 'ancient Ostia'], 'located in the administrative territorial entity': ['Rome', 'Rome, Italy'], 'location': ['Ostia'], 'instance of': ['archaeological sites'], 'country': ['Italy', 'Italian']}
{'merge_count': 11, 'type': ['archaeological site', 'ancient city'], 'title': 'San Giovanni di Posada'}

'Los Angeles' found in 'headquarters location':
{'name': ['California State University, Los Angeles', 'Los Angeles State', 'California State University at Los Angeles', 'Cal State Los Angeles', 'Los Angeles State College', 'California State Los Angeles', 'Luckman Fine Arts Complex', 'Los Angeles', 'Cal State LA', 'CSULA', 'California State University Los Angeles', 'Los Angeles State College of Applied Arts and Sciences', 'California State College'], 'headquarters location': ['Los Angeles, California', 'Los Angeles'], 'parent organization': ['CSU', 'California State University']}
{'merge_count': 17, 'type': ['university', 'public educational institution of the United States'], 'title': 'Silvia Heubach'}

'Magdalena' found in 'capital':
{'name': ['Magdalena Partido', 'Magdalena'], 'instance of': ['partido'], 'located in the administrative territorial entity': ['Buenos Aires Province'], 'country': ['Argentina'], 'capital': ['Magdalena']}
{'merge_count': 3, 'type': ['partido of Buenos Aires Province', 'municipality'], 'title': 'Punta Indio Partido'}

'Walt Disney Pictures' found in 'owned by':
{'name': ['Walt Disney Animation Studios', 'Disney', 'Walt Disney Productions', 'Walt Disney Studios', 'Disney Animation Studios', 'Walt Disney Feature Animation', "Disney's", 'Disney animated feature', 'Walt Disney Pictures', 'Disney animator', 'Disney studios', 'Disney Animation', 'The Walt Disney Studio', 'Walt Disney Production', 'Walt Disney Animation', 'Disney animated', 'Walt Disney', 'Walt Disney animated film', 'Disney Studio', 'Disney animated film', 'Walt Disney Studio’s', 'animated Disney films', 'Disney Feature Animation', 'animation facility branch', 'Disney animation department', 'Disney computer-animated films', 'Disney Artist', 'Walt Disney Studio', 'Disney computer animated', "Walt Disney Animation's", 'animation divisions'], 'instance of': ['animation studio'], 'owned by': ['Walt Disney Pictures', 'The Walt Disney Company', 'Walt Disney Productions', 'the Walt Disney Company'], 'parent organization': ['Walt Disney Studios', 'The Walt Disney Studios'], 'founded by': ['Roy O. Disney'], 'inception': ['October 16, 1923'], 'headquarters location': ['Burbank, California'], 'country': ['United States of America']}
{'merge_count': 45, 'type': ['animation studio', 'film production company'], 'title': 'Grace Bailey'}

'Kuwait National Guard' found in 'has part(s)':
{'name': ['Military of the State of Kuwait', 'Kuwait Military Forces', 'military of Kuwait', 'Kuwaiti Forces', 'Kuwait National Guard', 'Kuwait Armed Forces', 'Border Security Directorate', 'Military of Kuwait', 'Armed Forces'], 'has part(s)': ['Kuwait National Guard', 'Kuwait Army', 'Kuwait Naval Force', 'Kuwait Air Force'], 'country': ['State of Kuwait', 'Kuwait']}
{'merge_count': 12, 'type': ['armed forces'], 'title': 'Kuwait National Guard'}

'Amiens' found in 'located in the administrative territorial entity':
{'name': ['Cathedral of Notre-Dame in Amiens', 'Cathedral of Notre Dame in Amiens', 'Cathedral of Amiens', 'Amiens Cathedral', 'Amiens', 'cathedral of Notre Dame in Amiens'], 'architect': ['Robert de Luzarches', 'Robert of Luzarches'], 'diocese': ['Bishop of Amiens'], 'located in the administrative territorial entity': ['Amiens'], 'architectural style': ['Gothic architecture', 'Gothic'], 'heritage designation': ['World Heritage Site']}
{'merge_count': 7, 'type': ['Catholic cathedral', 'legal person'], 'title': 'Thomas de Cormont'}

'geographer' found in 'practiced by':
{'name': ['geography', 'geographical region', 'Geography', 'geographer', 'geographic', 'geographical', 'geographical reach', 'geographical science', 'geographic space', 'geographical name', 'geographical coverage', 'Geographically', 'geographers', 'geospatial', 'Geographical', 'geographical information', 'geographically', 'Greek geographers', 'space', 'surface of the earth', 'geographical sciences', 'features'], 'practiced by': ['geographer'], 'instance of': ['field of study', 'major', 'academic disciplines', 'academic discipline'], 'subclass of': ['social science']}
{'merge_count': 30, 'type': ['academic discipline', 'academic discipline', 'academic discipline'], 'title': 'Leroy Lansing Janes'}

'Tank' found in 'capital':
{'name': ['Tank', 'Tank District', 'Tank district'], 'country': ['Pakistan'], 'located in the administrative territorial entity': ['Dera Ismail Khan Division'], 'capital': ['Tank']}
{'merge_count': 6, 'type': ['district of Pakistan'], 'title': 'South Waziristan'}

'Vysshaya Liga' found in 'replaces':
{'name': ['Supreme Hockey League', 'Russian Major League', 'Vysshaya Liga', 'VHL', 'Higher Hockey League', 'Vysshaya Hokkeinaya Liga', 'Open Russian Championship', 'Major Hockey League', 'MHL', 'Vysshaya Hockey Liga', 'Vysshaya hokkeinaya liga'], 'sport': ['ice hockey'], 'organizer': ['Ice Hockey Federation of Russia'], 'country': ['Russian', 'Russia'], 'inception': ['2010'], 'sports league level': ['2'], 'number of participants': ['34'], 'replaces': ['Vysshaya Liga']}
{'merge_count': 27, 'type': ['sports league'], 'title': 'Humo Tashkent'}

'Calcutta' found in 'located in the administrative territorial entity':
{'name': ['University of Calcutta', 'Culcutta University', 'Calcutta University', 'Calcutta', 'Calcuttat (sic) University', 'University Institute Hall', 'Kolkata University'], 'located in the administrative territorial entity': ['Kolkata', 'Calcutta', 'Southern Kolkata'], 'inception': ['24 January 1857'], 'affiliation': ['University Grants Commission', 'UGC'], 'country': ['India']}
{'merge_count': 17, 'type': ['public university'], 'title': 'Narasinha Dutt College'}

'Chinese' found in 'subclass of':
{'name': ['Chinese-American', 'Chinese American', 'Chinese community', 'Chinese', 'Chinese-born American', 'Chinese Americans', 'Chinese immigrants', 'immigrant Chinese miners', 'Chinese in the U.S.', 'US', 'Chinese-born', 'United States.', 'Chinese–American', 'Chinese-Americans', 'Chinese descent'], 'subclass of': ['Asian American', 'Chinese', 'Asian Americans'], 'part of': ['Americans'], 'diaspora': ['Chinese diaspora', 'overseas Chinese']}
{'merge_count': 18, 'type': ['ethnic group'], 'title': 'Sharon Lin'}

'climbing' found in 'subclass of':
{'name': ['rock climbing', 'rock climber', 'rock', 'rock climbers', 'rock-climbing', 'climbing', 'rock climb', 'Rock climbing', 'technical climbing', 'climbers', 'technical climbs', 'rock climbs', 'summer climbing', 'rockclimber', 'climbing routes', 'mountaineers', 'rockclimbing', 'Rock climber', 'cliff climbing', 'technical rock climbs'], 'subclass of': ['climbing', 'style']}
{'merge_count': 26, 'type': ['type of sport', 'climbing discipline', 'hobby'], 'title': 'Slab climbing'}

'Premier League' found in 'sports season of league or competition':
{'name': ['2013–14 Premier League', '2013–14 title', '2013–14 season', '2013-14 season', '2013–14', 'league', 'Premier League'], 'winner': ['Manchester City'], 'sports season of league or competition': ['Premier League'], 'sport': ['football'], 'end time': ['11 May 2014']}
{'merge_count': 10, 'type': ['sports series'], 'title': '2014 FA Community Shield'}

'United Arab Emirates' found in 'country':
{'name': ['UAE', 'United Arab Emirates', 'United Arab Emirates Davis Cup team'], 'participant in': ['Davis Cup'], 'country': ['United Arab Emirates'], 'sport': ['tennis']}
{'merge_count': 4, 'type': ['Davis Cup team'], 'title': 'Fares Al Janahi'}

'Nicaragua' found in 'country':
{'name': ['Nicaragua', 'Nicaragua national baseball team'], 'sport': ['baseball'], 'country': ['Nicaragua']}
{'merge_count': 2, 'type': ['national baseball team'], 'title': '1939 Amateur World Series'}

'Chipiona' found in 'located in the administrative territorial entity':
{'name': ['Chipiona Lighthouse', 'Faro de Chipiona', 'Chipiona'], 'instance of': ['lighthouse'], 'located in the administrative territorial entity': ['Chipiona'], 'country': ['Spain'], 'located in or next to body of water': ['Atlantic Ocean']}
{'merge_count': 3, 'type': ['lighthouse'], 'title': 'Chipiona Lighthouse'}

'Low Saxon' found in 'language used':
{'name': ['Lower Saxony', 'Niedersachsen', 'Lower Saxon', 'Lower Saxonian', 'Saxon', 'niedersachsen', 'Saxony', 'Lower-Saxony', 'Lower Saxony, Germany', 'Low Saxon', "Lower Saxony's"], 'contains the administrative territorial entity': ['Emden', 'district of Wolfenbüttel', 'Gifhorn', 'Verden', 'district of Aurich', 'Wolfsburg', 'Ammerland', 'district of Osnabrück', 'Uelzen district', 'Braunschweig', 'district of Diepholz', 'district of Cuxhaven', 'district of Gifhorn', 'Göttingen', 'Oldenburg district', 'Hanover Region', 'Harburg', 'district of Helmstedt', 'district of Holzminden', 'Osterholz', 'district of Hanover', 'Heidekreis district', 'Wesermarsch', 'Celle district', 'district Peine', 'Stade', 'district of Stade', 'district Osnabrück', 'Leer district', 'Grafschaft Bentheim', 'Celle', 'district of Osterholz', 'district of Peine', 'district of Lüneburg', 'district of Hildesheim', 'district of Celle', 'district of Friesland', 'district of Oldenburg', 'district of Uelzen', 'Osnabrück', 'Hildesheim', 'Oldenburg', 'Aurich', 'district of Rotenburg', 'Emsland', 'district of Vechta', 'Salzgitter', 'Nienburg/Weser', 'Schaumburg', 'Uelzen', 'Lüchow-Dannenberg', 'Cloppenburg district', 'Delmenhorst', 'Wolfenbüttel', 'Northeim', 'Rotenburg', 'district of Goslar', 'Goslar', 'Leer', 'Holzminden', 'Nienburg/Weser district', 'district of Nienburg', 'district of Göttingen', 'Heidekreis', 'Goslar district', 'Bentheim', 'Soltau-Fallingbostel', 'Nienburg', 'Hameln-Pyrmont', 'Hanover region', 'Soltau-Fallingbostel district', 'Diepholz', 'Vechta', 'Weser-Ems', 'Aurich rural governmental district', 'Brunswick', 'Wolfenbüttel District', 'Leer District', 'Lüneburg', 'Lüneburg district', 'Friesland', 'Landkreis Grafschaft Bentheim', 'District of Lüneburg', 'Region Hannover', 'Wilhelmshaven', 'Cuxhaven', 'Wittmund', 'Peine', 'Helmstedt', 'Cuxhaven district', 'district of Leer', 'district Uelzen', 'Fallingbostel', 'Gifhorn district', 'Harburg district', 'Wolfenbüttel district', 'Landkreis Göttingen', 'Göttingen district', 'District of Göttingen', 'district', 'district of Cloppenburg', 'district of Northeim', 'Hamelin-Pyrmont', 'Goslar District', 'Cloppenburg', 'Vechta district', 'county of Uelzen', 'District of Wolfenbüttel', 'Gifhorn (district)', 'Holzminden district', 'Cloppenburg District', 'district of', 'Osnabrück district', 'Landkreis', 'district of Hannover', 'district of Schaumburg', 'district of Wittmund', 'Wendland', 'district of Verden', 'district Nienburg', 'Landkreis Osnabrück', 'Landkreis Emsland', 'Diepholz district', 'the eponymous district'], 'instance of': ['German state', 'German states', 'federal states', 'Bundesland', 'state', 'federal state', 'Länder', 'states', 'areas of', 'State', 'federated states', 'states of Germany'], 'country': ['Germany', 'German'], 'shares border with': ['Free Hanseatic City of Bremen', 'Saxony-Anhalt', 'North Rhine-Westphalia', 'Hamburg', 'Mecklenburg-Vorpommern', 'Hesse', 'Schleswig-Holstein', 'Thuringia', 'Bremen', 'Groningen', 'Drenthe', 'Overijssel', 'Brandenburg', 'Hessen', 'Hessian', 'Mecklenburg-Western Pomerania'], 'capital': ['Hannover', 'Hanover'], 'language used': ['Low Saxon', 'Low German', 'East Frisian Low Saxon', 'Saterland Frisian', 'low German'], 'located in the administrative territorial entity': ['Germany', 'German'], 'inception': ['November 1946', '1 November 1946'], 'office held by head of government': ['Minister President', 'Minister President of Lower Saxony'], 'has part(s)': ['Brunswick Land'], 'replaces': ['Oldenburg', 'State of Hanover'], 'legislative body': ['Landtag of Lower Saxony', 'parliament'], 'part of': ['Hamburg Metropolitan Region'], 'named after': ['Saxons']}
{'merge_count': 351, 'type': ['federated state of Germany'], 'title': 'Kleiner Knollen'}

'William Hazlitt' found in 'child':
{'name': ['William Hazlitt', 'Hazlitt'], 'date of death': ['1830', '18 September 1830'], 'notable work': ['The Spirit of the Age', 'Table-Talk'], 'date of birth': ['10 April 1778', '1778'], 'child': ['William Hazlitt'], 'father': ['William Hazlitt']}
{'merge_count': 9, 'type': ['human'], 'title': 'Ultracrepidarianism'}

'Miami' found in 'place served by transport hub':
{'name': ['Miami International Airport', '36th Street Airport', 'Miami Airport', 'Miami International Airport (MIA)', 'Miami'], 'place served by transport hub': ['Miami'], 'located in the administrative territorial entity': ['Miami-Dade County', 'metropolitan'], 'country': ['United States']}
{'merge_count': 9, 'type': ['international airport', 'commercial traffic aerodrome'], 'title': 'Carlos Zapata'}

'Yonne' found in 'named after':
{'name': ['Yonne', 'department of Yonne', "Yonne Department's", 'Yonne department'], 'instance of': ['department', 'departmental system', 'département', 'départements', 'French department'], 'located in the administrative territorial entity': ['Bourgogne-Franche-Comté'], 'country': ['France', 'French'], 'contains the administrative territorial entity': ['Treigny', 'Vézelay', 'Vassy-sous-Pisy', 'Sens', 'Aillant-sur-Tholon', 'Champcevrais', 'Saint-André-en-Terre-Plaine', 'Saint-Aubin-Château-Neuf', 'Sennevoy-le-Bas', 'Chastellux-sur-Cure', 'Vincelottes', 'Ancy-le-Franc', 'Auxerre', 'Soumaintrain', 'Taingy', 'Trévilly', 'Val-de-Mercy', 'Venoy', 'Villebougis', 'Villechétive', 'Villemanoche', 'Villeperrot', 'Villethierry', 'Villevallier', 'Chablis', 'Asquins', 'Champvallon', 'Chassignelles', 'Châtel-Censoir', 'Châtel-Gérard', 'Chitry', 'Cisery', 'Coulangeron', 'Courtois-sur-Yonne', 'Dicy', 'Gisy-les-Nobles', 'Guerchy', "L'Isle-sur-Serein", 'Joux-la-Ville', 'Laduz', 'Lainsecq', 'Paroy-en-Othe', 'Sainte-Magnance', 'Saint-Denis-lès-Sens', 'Sainte-Pallaye', 'Sainte-Vertu', 'Saint-Martin-sur-Armançon', 'Saint-Maurice-aux-Riches-Hommes', 'Saint-Sérotin', 'Saint-Martin-sur-Ouanne', 'Seignelay', 'Sementron', 'Sépeaux', 'Sermizelles', 'Mailly-la-Ville', 'Saint-Fargeau', 'Molesmes', 'Savigny-en-Terre-Plaine', 'Pacy-sur-Armançon', 'Irancy', 'Ouanne', 'Saint-Léger-Vauban', 'Sainte-Colombe-sur-Loing', 'Tanlay', 'Pont-sur-Yonne', 'Tonnerre', 'Pisy', 'Santigny', 'Serbonnes', 'Toucy', 'Égriselles-le-Bocage', 'Villeblevin', 'Branches', 'Joigny', 'Avallon', 'Domecy-sur-le-Vault', 'Domecy-sur-Cure', 'Aisy-sur-Armançon', 'Voutenay-sur-Cure', 'Carisey', 'Villeneuve-la-Guyard', 'Malay-le-Grand', 'Mailly-le-Château', 'Malay-le-Petit', 'Marchais-Beton', 'Pimelles', 'Bellechaume', 'Theil-sur-Vanne', 'La Postolle', 'Courgenay', 'Saint-Bris-le-Vineux', 'Ancy-le-Libre', 'Annay-sur-Serein', 'Annay-la-Côte', 'Appoigny', 'Asnières-sous-Bois', 'Argenteuil-sur-Armançon', 'Arcy-sur-Cure', 'Bazarnes', 'Bierry-les-Belles-Fontaines', 'La Belliole', 'Bleigny-le-Carreau', 'Migé', 'Mézilles', 'Merry-sur-Yonne', 'Moutiers-en-Puisaye', 'Moulins-sur-Ouanne', 'Mont-Saint-Sulpice', 'Montigny-la-Resle', 'Montacher-Villegardin', 'Mouffy', 'Moulins-en-Tonnerrois', 'Neuvy-Sautour', 'Nuits', 'Brienon-sur-Armançon', 'La Celle-Saint-Cyr', 'Paroy-sur-Tholon', 'Bussy-en-Othe', 'Perrigny-sur-Armançon', 'Pierre-Perthuis', 'Poilly-sur-Serein', 'Poilly-sur-Tholon', 'Pont-sur-Vanne', 'Précy-le-Sec', 'Précy-sur-Vrin', 'Chambeugle', 'Prunoy', 'Rogny-les-Sept-Écluses', 'Ligny-le-Châtel', 'Volgré', 'Champignelles', 'Villiers-les-Hauts', 'Villiers-Louis', 'Villiers-Saint-Benoît', 'Villiers-Vineux', 'Villiers-sur-Tholon', 'Lichères-sur-Yonne', 'Lignorelles', 'Lichères-près-Aigremont', 'Épineau-les-Voves', 'Trucy-sur-Yonne', 'Fontenay-près-Chablis', 'Sougères-en-Puisaye', 'Fontenay-près-Vézelay', 'Fontenay-sous-Fouronnes', 'Fontenouilles', 'Fouronnes', 'Fleury-la-Vallée', 'Chigy', 'Saint-Brancher', 'Saint-Cyr-les-Colons', 'Saint-Aubin-sur-Yonne', 'Saint-Georges-sur-Baulche', 'Saint-Germain-des-Champs', "Saint-Loup-d'Ordon", 'Sauvigny-le-Beuréal', 'Sauvigny-le-Bois', 'Savigny-sur-Clairis', 'Saint-Romain-le-Preux', 'Saint-Sauveur-en-Puisaye', 'Coulanges-la-Vineuse', 'Druyes-les-Belles-Fontaines', 'Coulanges-sur-Yonne', 'Fontaine-la-Gaillarde', 'Sennevoy-le-Haut', 'La Chapelle-sur-Oreuse', 'Thorigny-sur-Oreuse', 'Tannerre-en-Puisaye', 'Escolives-Sainte-Camille', 'Cussy-les-Forges', 'Flogny-la-Chapelle', 'Foissy-lès-Vézelay', "Saint-Martin-d'Ordon", 'Foissy-sur-Vanne', 'Saint-Maurice-le-Vieil', 'Saint-Maurice-Thizouaille', 'Saints-en-Puisaye', 'La Chapelle-Vaupelteigne', 'Chemilly-sur-Serein', 'Chemilly-sur-Yonne', 'Charentenay', 'Sainpuits', 'Courson-les-Carrières', 'Vault-de-Lugny', "Gy-l'Évêque", 'Saint-Denis-sur-Ouanne', 'Chêne-Arnoult', 'Laroche-Saint-Cydroine', 'Courlon-sur-Yonne', 'Dyé', 'La Ferté-Loupière', 'Étais-la-Sauvin', "Villeneuve-l'Archevêque", 'Lucy-sur-Cure', 'Villeneuve-les-Genêts', 'Lucy-sur-Yonne', 'Villeneuve-la-Dondagre', 'Villenavotte', 'Lucy-le-Bois', 'Villefargeau', 'Villeneuve-Saint-Salves', 'Vallery', 'Villeneuve-sur-Yonne', 'Arrondissement of Sens', 'Percey', 'Pontigny', 'Les Clérimois', 'Coutarnoux', 'Cruzy-le-Châtel', 'Andryes', 'Bessy-sur-Cure', 'Bœurs-en-Othe', 'Bléneau', 'Merry-la-Vallée', 'Merry-Sec', 'Quarré-les-Tombes', 'Saint-Julien-du-Sault'], 'shares border with': ['Loiret', 'Seine-et-Marne'], 'capital': ['Auxerre'], 'named after': ['Yonne']}
{'merge_count': 252, 'type': ['department of France'], 'title': 'Treigny'}

'Colombia' found in 'country':
{'name': ['Colombia', 'Colombia national futsal team'], 'country': ['Colombia'], 'sport': ['futsal']}
{'merge_count': 2, 'type': ['national futsal team'], 'title': "2011 AMF Futsal Men's World Cup"}

'PIM' found in 'instance of':
{'name': ['Kontact', 'KMail', 'PIM', 'Kmail', 'Korganizer'], 'instance of': ['PIM', 'free software', 'personal information manager'], 'developer': ['KDE']}
{'merge_count': 8, 'type': ['free software', 'personal information manager'], 'title': 'Kolab'}

'Hungary' found in 'country':
{'name': ['Hungarian', 'Hungarians', 'Hungarian people', 'Magyars', 'ethnic Hungarian', 'Hungarian descent', 'Hungarian nation', 'Magyar', 'ethnic Hungarians', 'Hungarian territory', 'Magyar people', 'Hungaria', 'Hungarian ethnicity', 'Hungarian nationality', 'Hungarian origin', 'Hungarian:', 'hungarian', 'Hungarian-speaking', 'people', 'Hungarian-born American', 'Hungary', 'magyar'], 'country': ['Romania', 'Slovakia', 'Hungary', 'Ukraine', 'Serbia', 'Canada'], 'has part(s)': ['Hungarian diaspora', 'Szekler', 'Csangos', 'Székely', 'Significant groups', 'Székelys', 'Csángós', 'Szeklers'], 'instance of': ['ethnic group', 'ethnic community', 'ethnicity'], 'religion or worldview': ['Roman Catholic', 'Catholic'], 'part of': ['Finno-Ugric', 'Finno-Ugric peoples']}
{'merge_count': 57, 'type': ['ethnic group'], 'title': 'Júlia Hajdú'}

'Championship' found in 'sports season of league or competition':
{'name': ['2013–14 Football League Championship', '2013–14 season', 'Championship'], 'sports season of league or competition': ['Football League Championship', 'Championship'], 'end time': ['3 May 2014']}
{'merge_count': 5, 'type': ['sports series'], 'title': '2013–14 Football League Championship'}

'Uruguay' found in 'country for sport':

In [8]:
# compute counts of property occurrence and entity types of the fragments
property_counts = defaultdict(int)
type_counts = defaultdict(int)

for fragment in fragments:
    for prop_name, prop_value in fragment.properties.items():
        if prop_value:
            property_counts[prop_name] += 1

    if fragment.wikidata_type:
        for ent_type in fragment.wikidata_type:
            type_counts[ent_type] += 1

Top properties by occurrence in the fragments
---

In [9]:
df = (
    pd.DataFrame(property_counts.items(), columns=["property", "count"])
    .sort_values(by="count", ascending=False)
    .reset_index(drop=True)
)

if save_statistics:
    df.to_csv("property_occurrence.csv", index=False)

df[:20]

                                            property  count
0                                               name   5108
1   located in the administrative territorial entity   1342
2                                            country   1277
3                                        instance of    967
4                                      date of birth    786
5                                              sport    457
6                                      point in time    445
7                                          inception    380
8                                      date of death    355
9                                            part of    327
10                                    place of birth    283
11                                shares border with    278
12                                          location    204
13                                  publication date    176
14                                         performer    160
15                                             genre    153
16                            country of citizenship    151
17                                       has part(s)    128
18                             headquarters location    127
19                                       educated at    116

Top entity types of the fragments
---

In [10]:
df = (
    pd.DataFrame(type_counts.items(), columns=["type", "count"])
    .sort_values(by="count", ascending=False)
    .reset_index(drop=True)
)

if save_statistics:
    df.to_csv("type_occurrence.csv", index=False)

df[:20]

                             type  count
0                           human   1098
1                   sports series    177
2                commune of Italy    145
3                           river     73
4                           album     70
5                            film     70
6   American football team season     68
7                human settlement     55
8               commune of France     51
9                     corporation     50
10       musical work/composition     50
11                          Kuppe     48
12                  musical group     46
13                        village     45
14                          taxon     43
15                       big city     36
16                           city     36
17                         single     36
18      association football club     36
19                  literary work     32

Fragments per entity
---

In [11]:
entity_ids = [fragment.entity_id for fragment in fragments]
counts = pd.Series(entity_ids).value_counts().value_counts().sort_index()

fig = px.bar(counts, x=counts.index.astype(str), y=counts.values, title="Fragments per entity", text=counts.values)
fig.update_layout(xaxis_title="", yaxis_title="Count", width=800, height=600)
fig.show()

avg_fragments_per_entity = pd.Series(entity_ids).value_counts().mean()
print(f"Average fragments per entity: {avg_fragments_per_entity:.2f}")

Average fragments per entity: 1.03

Fragments sizes (if merged)
---

In [12]:
merge_counts = [fragment.metadata["merge_count"] if "merge_count" in fragment.metadata else 1 for fragment in fragments]

counts = pd.Series(merge_counts).value_counts().sort_index()
fig = px.bar(
    counts, x=counts.index.astype(str), y=counts.values, title="Fragment sizes (if merged)", text=counts.values
)
fig.update_layout(xaxis_title="Fragment size", yaxis_title="Count", width=800, height=600)
fig.show()

Properties overlap
---

In [13]:
# for each property how often that two distinct fragments have (1) a value for this property, and (2) the same value this property
property_value_counts = defaultdict(lambda: defaultdict(int))
entity_value_counts = defaultdict(int)

for entity_id in fragments:
    for prop_name, values in entity_id.properties.items():
        entity_value_counts[prop_name] += 1
        for value in values:
            property_value_counts[prop_name][value] += 1

entity_count = len(fragments)

rows = []
for prop_name, value_counts in property_value_counts.items():
    arr = np.array(list(value_counts.values()))
    ent_val_count = entity_value_counts[prop_name]
    ent_probs = arr / entity_count
    cond_ent_probs = arr / ent_val_count
    prob = (ent_probs**2).sum()
    cond_prob = (cond_ent_probs**2).sum()
    ent_fraction = ent_val_count / entity_count
    rows.append((prop_name, len(value_counts), prob, cond_prob, ent_fraction))

overlap_df = pd.DataFrame(
    rows, columns=["property", "distinct_value_count", "overlap_prob", "cond_overlap_prob", "entities_fraction"]
)
overlap_df = overlap_df.sort_values("overlap_prob", ascending=False)
overlap_df.head(100)

,property,distinct_value_count,overlap_prob,cond_overlap_prob,entities_fraction
3,country,306,0.001540,0.024648,0.250000
1,instance of,652,0.000996,0.027781,0.189311
7,sport,105,0.000915,0.114307,0.089468
0,name,13094,0.000596,0.000596,1.000000
2,located in the administrative territorial entity,1317,0.000134,0.001937,0.262725
...,...,...,...,...,...
322,student,31,0.000001,0.861111,0.001175
131,screenwriter,29,0.000001,0.050347,0.004699
109,candidate,28,0.000001,0.571429,0.001370
26,highest point,27,0.000001,0.043200,0.004894
81,"product, material, or service produced or prov...",24,0.000001,0.120000,0.002937